@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package arekkuusu.enderskills.common.potion;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;