@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package arekkuusu.enderskills.common.skill.ability.offence.electric;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;