package arekkuusu.enderskills.common.sound;

import arekkuusu.enderskills.common.lib.LibMod;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.registries.IForgeRegistry;

import javax.annotation.Nonnull;

@GameRegistry.ObjectHolder(LibMod.MOD_ID)
public final class ModSounds {

    @Nonnull
    @SuppressWarnings("ConstantConditions")
    public static SoundEvent empty() {
        return null;
    }

    public static final SoundEvent PAGE_TURN = empty();
    public static final SoundEvent SPARK = empty();
    public static final SoundEvent PORTAL_PLACE = empty();
    public static final SoundEvent PORTAL_ACTIVE = empty();
    public static final SoundEvent PORTAL_CLOSED_ACTIVE = empty();
    public static final SoundEvent PORTAL_OPEN = empty();
    public static final SoundEvent TELEPORT = empty();
    public static final SoundEvent UNSTABLE_PORTAL = empty();
    public static final SoundEvent WARP = empty();
    public static final SoundEvent INVISIBILITY = empty();
    public static final SoundEvent HOVER = empty();
    public static final SoundEvent SMASH_HIT = empty();
    public static final SoundEvent SMASH_START = empty();
    public static final SoundEvent SPEED = empty();
    public static final SoundEvent DASH = empty();
    public static final SoundEvent FOG = empty();
    public static final SoundEvent HASTEN = empty();
    public static final SoundEvent JUMP = empty();
    public static final SoundEvent PUSH = empty();
    public static final SoundEvent PULL = empty();
    public static final SoundEvent SLASH = empty();
    public static final SoundEvent UPDRAFT = empty();
    public static final SoundEvent WIND_ON_HIT = empty();
    public static final SoundEvent SUFFOCATE = empty();
    public static final SoundEvent SUFFOCATE_ACTIVE = empty();
    public static final SoundEvent CRUSH = empty();
    public static final SoundEvent TAUNT = empty();
    public static final SoundEvent THORNS = empty();
    public static final SoundEvent WALL_UP = empty();
    public static final SoundEvent WALL_DOWN = empty();
    public static final SoundEvent ANIMATED_STONE = empty();
    public static final SoundEvent DOME_DOWN = empty();
    public static final SoundEvent DOME_UP = empty();
    public static final SoundEvent EARTH_HIT = empty();
    public static final SoundEvent SHOCKWAVE = empty();
    public static final SoundEvent CONTAMINATE = empty();
    public static final SoundEvent BLOODPOOL_ACTIVE = empty();
    public static final SoundEvent BLOODPOOL = empty();
    public static final SoundEvent LIFE_STEAL = empty();
    public static final SoundEvent LIFE_STEAL_ATTACK = empty();
    public static final SoundEvent SACRIFICE = empty();
    public static final SoundEvent SACRIFICE_ACTIVE = empty();
    public static final SoundEvent SYPHON = empty();
    public static final SoundEvent BLEED = empty();
    public static final SoundEvent BLEED_ACTIVE = empty();
    public static final SoundEvent GAS_CLOUD = empty();
    public static final SoundEvent GAS_CLOUD_EXPLODE = empty();
    public static final SoundEvent GLOOM = empty();
    public static final SoundEvent GRASP = empty();
    public static final SoundEvent GRASP_ACTIVE = empty();
    public static final SoundEvent VOID_HIT = empty();
    public static final SoundEvent SHADOW = empty();
    public static final SoundEvent SHADOW_ATTACK = empty();
    public static final SoundEvent SHADOWJAB = empty();
    public static final SoundEvent BLACKHOLE = empty();
    public static final SoundEvent BLACKHOLE_ACTIVE = empty();
    public static final SoundEvent FIRE_HIT = empty();
    public static final SoundEvent FIRE_SPIRIT = empty();
    public static final SoundEvent FIRE_SPIRIT_ACTIVE = empty();
    public static final SoundEvent FIRE_SPIRIT_ACTIVE_ = empty();
    public static final SoundEvent FIREBALL = empty();
    public static final SoundEvent FIREBALL_EXPLODE = empty();
    public static final SoundEvent FLAMING_BREATH = empty();
    public static final SoundEvent FLAMING_RAIN = empty();
    public static final SoundEvent FLAMING_RAIN_ACTIVE = empty();
    public static final SoundEvent FOCUS_FLAME = empty();
    public static final SoundEvent EXPLODE = empty();
    public static final SoundEvent HEAL_AURA = empty();
    public static final SoundEvent HEAL_OTHER = empty();
    public static final SoundEvent HEAL_SELF = empty();
    public static final SoundEvent NEARBY_INVINCIBILITY = empty();
    public static final SoundEvent POWER_BOOST = empty();
    public static final SoundEvent CHARM = empty();
    public static final SoundEvent LIGHT_HIT = empty();
    public static final SoundEvent ELECTRIC_HIT = empty();
    public static final SoundEvent ELECTRIC_STUN = empty();
    public static final SoundEvent ELECTRIC_PULSE = empty();
    public static final SoundEvent ENERGIZE = empty();
    public static final SoundEvent MAGNETIC_PULL = empty();
    public static final SoundEvent POWER_DRAIN = empty();
    public static final SoundEvent SHOCKING_AURA = empty();
    public static final SoundEvent VOLTAIC_SENTINEL_SUMMON = empty();
    public static final SoundEvent VOLTAIC_SENTINEL_V1 = empty();
    public static final SoundEvent VOLTAIC_SENTINEL_V2 = empty();
    public static final SoundEvent BLAZING_AURA_ACTIVE = empty();
    public static final SoundEvent FLARES = empty();
    public static final SoundEvent FLARES_ACTIVE = empty();
    public static final SoundEvent OVERHEAT_ACTIVE = empty();
    public static final SoundEvent RING_OF_FIRE = empty();
    public static final SoundEvent WARM_HEART = empty();
    public static final SoundEvent HOME_STAR_ACTIVE = empty();
    public static final SoundEvent HOME_STAR_BOOM = empty();
    public static final SoundEvent BARRAGE_WHISPS_CAST = empty();
    public static final SoundEvent BARRAGE_WHISPS_RELEASE = empty();
    public static final SoundEvent FINAL_FLASH_CAST = empty();
    public static final SoundEvent FINAL_FLASH_RELEASE = empty();
    public static final SoundEvent GLEAM_BANG_CAST = empty();
    public static final SoundEvent GLEAM_BANG_RELEASE = empty();
    public static final SoundEvent LUMIN_WAVE_CAST = empty();
    public static final SoundEvent LUMIN_WAVE_RELEASE = empty();
    public static final SoundEvent OFFLIGHT_ONHIT = empty();
    public static final SoundEvent PASSIVE_POP = empty();
    public static final SoundEvent RADIANT_RAY_CAST = empty();
    public static final SoundEvent RADIANT_RAY_RELEASE = empty();
    public static final SoundEvent SOLAR_LANCE_CAST = empty();

    public static void register(IForgeRegistry<SoundEvent> registry) {
        registry.register(new SoundBase("page_turn"));
        registry.register(new SoundBase("spark"));
        registry.register(new SoundBase("portal_place"));
        registry.register(new SoundBase("portal_active"));
        registry.register(new SoundBase("portal_closed_active"));
        registry.register(new SoundBase("portal_open"));
        registry.register(new SoundBase("teleport"));
        registry.register(new SoundBase("unstable_portal"));
        registry.register(new SoundBase("warp"));
        registry.register(new SoundBase("invisibility"));
        registry.register(new SoundBase("hover"));
        registry.register(new SoundBase("smash_hit"));
        registry.register(new SoundBase("smash_start"));
        registry.register(new SoundBase("dash"));
        registry.register(new SoundBase("speed"));
        registry.register(new SoundBase("fog"));
        registry.register(new SoundBase("hasten"));
        registry.register(new SoundBase("jump"));
        registry.register(new SoundBase("pull"));
        registry.register(new SoundBase("push"));
        registry.register(new SoundBase("slash"));
        registry.register(new SoundBase("updraft"));
        registry.register(new SoundBase("wind_on_hit"));
        registry.register(new SoundBase("suffocate"));
        registry.register(new SoundBase("suffocate_active"));
        registry.register(new SoundBase("crush"));
        registry.register(new SoundBase("taunt"));
        registry.register(new SoundBase("thorns"));
        registry.register(new SoundBase("wall_down"));
        registry.register(new SoundBase("wall_up"));
        registry.register(new SoundBase("animated_stone"));
        registry.register(new SoundBase("dome_down"));
        registry.register(new SoundBase("dome_up"));
        registry.register(new SoundBase("earth_hit"));
        registry.register(new SoundBase("shockwave"));
        registry.register(new SoundBase("contaminate"));
        registry.register(new SoundBase("bloodpool_active"));
        registry.register(new SoundBase("bloodpool"));
        registry.register(new SoundBase("life_steal"));
        registry.register(new SoundBase("life_steal_attack"));
        registry.register(new SoundBase("sacrifice"));
        registry.register(new SoundBase("sacrifice_active"));
        registry.register(new SoundBase("syphon"));
        registry.register(new SoundBase("bleed"));
        registry.register(new SoundBase("bleed_active"));
        registry.register(new SoundBase("gas_cloud_explode"));
        registry.register(new SoundBase("gloom"));
        registry.register(new SoundBase("grasp"));
        registry.register(new SoundBase("grasp_active"));
        registry.register(new SoundBase("void_hit"));
        registry.register(new SoundBase("shadow"));
        registry.register(new SoundBase("shadow_attack"));
        registry.register(new SoundBase("shadowjab"));
        registry.register(new SoundBase("blackhole"));
        registry.register(new SoundBase("blackhole_active"));
        registry.register(new SoundBase("gas_cloud"));
        registry.register(new SoundBase("fire_hit"));
        registry.register(new SoundBase("fire_spirit"));
        registry.register(new SoundBase("fire_spirit_active"));
        registry.register(new SoundBase("fire_spirit_active_"));
        registry.register(new SoundBase("fireball"));
        registry.register(new SoundBase("fireball_explode"));
        registry.register(new SoundBase("flaming_rain"));
        registry.register(new SoundBase("focus_flame"));
        registry.register(new SoundBase("flaming_rain_active"));
        registry.register(new SoundBase("explode"));
        registry.register(new SoundBase("flaming_breath"));
        registry.register(new SoundBase("heal_aura"));
        registry.register(new SoundBase("heal_other"));
        registry.register(new SoundBase("heal_self"));
        registry.register(new SoundBase("nearby_invincibility"));
        registry.register(new SoundBase("power_boost"));
        registry.register(new SoundBase("charm"));
        registry.register(new SoundBase("light_hit"));
        registry.register(new SoundBase("electric_hit"));
        registry.register(new SoundBase("electric_stun"));
        registry.register(new SoundBase("electric_pulse"));
        registry.register(new SoundBase("energize"));
        registry.register(new SoundBase("magnetic_pull"));
        registry.register(new SoundBase("power_drain"));
        registry.register(new SoundBase("shocking_aura"));
        registry.register(new SoundBase("voltaic_sentinel_summon"));
        registry.register(new SoundBase("voltaic_sentinel_v1"));
        registry.register(new SoundBase("voltaic_sentinel_v2"));
        registry.register(new SoundBase("blazing_aura_active"));
        registry.register(new SoundBase("flares"));
        registry.register(new SoundBase("flares_active"));
        registry.register(new SoundBase("overheat_active"));
        registry.register(new SoundBase("ring_of_fire"));
        registry.register(new SoundBase("warm_heart"));
        registry.register(new SoundBase("home_star_active"));
        registry.register(new SoundBase("home_star_boom"));
        registry.register(new SoundBase("barrage_whisps_cast"));
        registry.register(new SoundBase("barrage_whisps_release"));
        registry.register(new SoundBase("final_flash_cast"));
        registry.register(new SoundBase("final_flash_release"));
        registry.register(new SoundBase("gleam_bang_cast"));
        registry.register(new SoundBase("gleam_bang_release"));
        registry.register(new SoundBase("lumin_wave_cast"));
        registry.register(new SoundBase("lumin_wave_release"));
        registry.register(new SoundBase("offlight_onhit"));
        registry.register(new SoundBase("passive_pop"));
        registry.register(new SoundBase("radiant_ray_cast"));
        registry.register(new SoundBase("radiant_ray_release"));
        registry.register(new SoundBase("solar_lance_cast"));
    }
}
