@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package arekkuusu.enderskills.client.util.resource;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;