@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package arekkuusu.enderskills.client.render.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;