@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package arekkuusu.enderskills.common.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;