package arekkuusu.enderskills.common.handler;

import arekkuusu.enderskills.common.lib.LibNames;
import arekkuusu.enderskills.common.skill.ModAbilities;
import arekkuusu.enderskills.common.skill.ModAttributes;

public class Advancements {
    public static void initializeAdvancements() {
        GuiHandler.setAdvancement(LibNames.DAMAGE_RESISTANCE, ModAttributes.DAMAGE_RESISTANCE);
        GuiHandler.setAdvancement(LibNames.EXPLOSION_RESISTANCE, ModAttributes.EXPLOSION_RESISTANCE);
        GuiHandler.setAdvancement(LibNames.FIRE_RESISTANCE, ModAttributes.FIRE_RESISTANCE);
        GuiHandler.setAdvancement(LibNames.HEART_BOOST, ModAttributes.HEART_BOOST);
        GuiHandler.setAdvancement(LibNames.KNOCKBACK_RESISTANCE, ModAttributes.KNOCKBACK_RESISTANCE);
        GuiHandler.setAdvancement(LibNames.MAGIC_RESISTANCE, ModAttributes.MAGIC_RESISTANCE);
        GuiHandler.setAdvancement(LibNames.ENDURANCE, ModAttributes.ENDURANCE);
        GuiHandler.setAdvancement(LibNames.FALL_RESISTANCE, ModAttributes.FALL_RESISTANCE);
        GuiHandler.setAdvancement(LibNames.JUMP_HEIGHT, ModAttributes.JUMP_HEIGHT);
        GuiHandler.setAdvancement(LibNames.SPEED, ModAttributes.SPEED);
        GuiHandler.setAdvancement(LibNames.STEALTH_DAMAGE, ModAttributes.STEALTH_DAMAGE);
        GuiHandler.setAdvancement(LibNames.SWIM_SPEED, ModAttributes.SWIM_SPEED);
        GuiHandler.setAdvancement(LibNames.ABILITY_DURATION, ModAttributes.ABILITY_DURATION);
        GuiHandler.setAdvancement(LibNames.ABILITY_POWER, ModAttributes.ABILITY_POWER);
        GuiHandler.setAdvancement(LibNames.ABILITY_RANGE, ModAttributes.ABILITY_RANGE);
        GuiHandler.setAdvancement(LibNames.ARMOR_PENETRATION, ModAttributes.ARMOR_PENETRATION);
        GuiHandler.setAdvancement(LibNames.ATTACK_SPEED, ModAttributes.ATTACK_SPEED);
        GuiHandler.setAdvancement(LibNames.CRITICAL_CHANCE, ModAttributes.CRITICAL_CHANCE);
        GuiHandler.setAdvancement(LibNames.KNOCKBACK, ModAttributes.KNOCKBACK);
        GuiHandler.setAdvancement(LibNames.DAMAGE, ModAttributes.DAMAGE);
        //
        GuiHandler.setAdvancement(LibNames.ANIMATED_STONE_GOLEM, ModAbilities.ANIMATED_STONE_GOLEM, ModAbilities.TAUNT);
        GuiHandler.setAdvancement(LibNames.DOME, ModAbilities.DOME, ModAbilities.TAUNT);
        GuiHandler.setAdvancement(LibNames.SHOCKWAVE, ModAbilities.SHOCKWAVE, ModAbilities.TAUNT);
        GuiHandler.setAdvancement(LibNames.TAUNT, ModAbilities.TAUNT, ModAbilities.TAUNT);
        GuiHandler.setAdvancement(LibNames.THORNY, ModAbilities.THORNY, ModAbilities.TAUNT);
        GuiHandler.setAdvancement(LibNames.WALL, ModAbilities.WALL, ModAbilities.TAUNT);
        GuiHandler.setAdvancement(LibNames.ELECTRIC_PULSE, ModAbilities.ELECTRIC_PULSE, ModAbilities.SHOCKING_AURA);
        GuiHandler.setAdvancement(LibNames.ENERGIZE, ModAbilities.ENERGIZE, ModAbilities.SHOCKING_AURA);
        GuiHandler.setAdvancement(LibNames.MAGNETIC_PULL, ModAbilities.MAGNETIC_PULL, ModAbilities.SHOCKING_AURA);
        GuiHandler.setAdvancement(LibNames.POWER_DRAIN, ModAbilities.POWER_DRAIN, ModAbilities.SHOCKING_AURA);
        GuiHandler.setAdvancement(LibNames.SHOCKING_AURA, ModAbilities.SHOCKING_AURA, ModAbilities.SHOCKING_AURA);
        GuiHandler.setAdvancement(LibNames.VOLTAIC_SENTINEL, ModAbilities.VOLTAIC_SENTINEL, ModAbilities.SHOCKING_AURA);
        GuiHandler.setAdvancement(LibNames.BLAZING_AURA, ModAbilities.BLAZING_AURA, ModAbilities.FLARES);
        GuiHandler.setAdvancement(LibNames.FLARES, ModAbilities.FLARES, ModAbilities.FLARES);
        GuiHandler.setAdvancement(LibNames.HOME_STAR, ModAbilities.HOME_STAR, ModAbilities.FLARES);
        GuiHandler.setAdvancement(LibNames.OVERHEAT, ModAbilities.OVERHEAT, ModAbilities.FLARES);
        GuiHandler.setAdvancement(LibNames.RING_OF_FIRE, ModAbilities.RING_OF_FIRE, ModAbilities.FLARES);
        GuiHandler.setAdvancement(LibNames.WARM_HEART, ModAbilities.WARM_HEART, ModAbilities.FLARES);
        GuiHandler.setAdvancement(LibNames.CHARM, ModAbilities.CHARM, ModAbilities.CHARM);
        GuiHandler.setAdvancement(LibNames.HEAL_AURA, ModAbilities.HEAL_AURA, ModAbilities.CHARM);
        GuiHandler.setAdvancement(LibNames.HEAL_OTHER, ModAbilities.HEAL_OTHER, ModAbilities.CHARM);
        GuiHandler.setAdvancement(LibNames.HEAL_SELF, ModAbilities.HEAL_SELF, ModAbilities.CHARM);
        GuiHandler.setAdvancement(LibNames.NEARBY_INVINCIBILITY, ModAbilities.NEARBY_INVINCIBILITY, ModAbilities.CHARM);
        GuiHandler.setAdvancement(LibNames.POWER_BOOST, ModAbilities.POWER_BOOST, ModAbilities.CHARM);
        GuiHandler.setAdvancement(LibNames.HOVER, ModAbilities.HOVER, ModAbilities.WARP);
        GuiHandler.setAdvancement(LibNames.INVISIBILITY, ModAbilities.INVISIBILITY, ModAbilities.WARP);
        GuiHandler.setAdvancement(LibNames.PORTAL, ModAbilities.PORTAL, ModAbilities.WARP);
        GuiHandler.setAdvancement(LibNames.TELEPORT, ModAbilities.TELEPORT, ModAbilities.WARP);
        GuiHandler.setAdvancement(LibNames.UNSTABLE_PORTAL, ModAbilities.UNSTABLE_PORTAL, ModAbilities.WARP);
        GuiHandler.setAdvancement(LibNames.WARP, ModAbilities.WARP, ModAbilities.WARP);
        GuiHandler.setAdvancement(LibNames.DASH, ModAbilities.DASH, ModAbilities.DASH);
        GuiHandler.setAdvancement(LibNames.EXTRA_JUMP, ModAbilities.EXTRA_JUMP, ModAbilities.DASH);
        GuiHandler.setAdvancement(LibNames.FOG, ModAbilities.FOG, ModAbilities.DASH);
        GuiHandler.setAdvancement(LibNames.HASTEN, ModAbilities.HASTEN, ModAbilities.DASH);
        GuiHandler.setAdvancement(LibNames.SMASH, ModAbilities.SMASH, ModAbilities.DASH);
        GuiHandler.setAdvancement(LibNames.SPEED_BOOST, ModAbilities.SPEED_BOOST, ModAbilities.DASH);
        GuiHandler.setAdvancement(LibNames.BLEED, ModAbilities.BLEED, ModAbilities.BLEED);
        GuiHandler.setAdvancement(LibNames.BLOOD_POOL, ModAbilities.BLOOD_POOL, ModAbilities.BLEED);
        GuiHandler.setAdvancement(LibNames.CONTAMINATE, ModAbilities.CONTAMINATE, ModAbilities.BLEED);
        GuiHandler.setAdvancement(LibNames.LIFE_STEAL, ModAbilities.LIFE_STEAL, ModAbilities.BLEED);
        GuiHandler.setAdvancement(LibNames.SACRIFICE, ModAbilities.SACRIFICE, ModAbilities.BLEED);
        GuiHandler.setAdvancement(LibNames.SYPHON, ModAbilities.SYPHON, ModAbilities.BLEED);
        GuiHandler.setAdvancement(LibNames.BLACK_HOLE, ModAbilities.BLACK_HOLE, ModAbilities.SHADOW);
        GuiHandler.setAdvancement(LibNames.GAS_CLOUD, ModAbilities.GAS_CLOUD, ModAbilities.SHADOW);
        GuiHandler.setAdvancement(LibNames.GLOOM, ModAbilities.GLOOM, ModAbilities.SHADOW);
        GuiHandler.setAdvancement(LibNames.GRASP, ModAbilities.GRASP, ModAbilities.SHADOW);
        GuiHandler.setAdvancement(LibNames.SHADOW, ModAbilities.SHADOW, ModAbilities.SHADOW);
        GuiHandler.setAdvancement(LibNames.SHADOW_JAB, ModAbilities.SHADOW_JAB, ModAbilities.SHADOW);
        GuiHandler.setAdvancement(LibNames.EXPLODE, ModAbilities.EXPLODE, ModAbilities.FIRE_SPIRIT);
        GuiHandler.setAdvancement(LibNames.FIREBALL, ModAbilities.FIREBALL, ModAbilities.FIRE_SPIRIT);
        GuiHandler.setAdvancement(LibNames.FIRE_SPIRIT, ModAbilities.FIRE_SPIRIT, ModAbilities.FIRE_SPIRIT);
        GuiHandler.setAdvancement(LibNames.FLAMING_BREATH, ModAbilities.FLAMING_BREATH, ModAbilities.FIRE_SPIRIT);
        GuiHandler.setAdvancement(LibNames.FLAMING_RAIN, ModAbilities.FLAMING_RAIN, ModAbilities.FIRE_SPIRIT);
        GuiHandler.setAdvancement(LibNames.FOCUS_FLAME, ModAbilities.FOCUS_FLAME, ModAbilities.FIRE_SPIRIT);
        GuiHandler.setAdvancement(LibNames.BARRAGE_WISPS, ModAbilities.BARRAGE_WISPS, ModAbilities.RADIANT_RAY);
        GuiHandler.setAdvancement(LibNames.FINAL_FLASH, ModAbilities.FINAL_FLASH, ModAbilities.RADIANT_RAY);
        GuiHandler.setAdvancement(LibNames.GLEAM_FLASH, ModAbilities.GLEAM_FLASH, ModAbilities.RADIANT_RAY);
        GuiHandler.setAdvancement(LibNames.LUMEN_WAVE, ModAbilities.LUMEN_WAVE, ModAbilities.RADIANT_RAY);
        GuiHandler.setAdvancement(LibNames.RADIANT_RAY, ModAbilities.RADIANT_RAY, ModAbilities.RADIANT_RAY);
        GuiHandler.setAdvancement(LibNames.SOLAR_LANCE, ModAbilities.SOLAR_LANCE, ModAbilities.RADIANT_RAY);
        GuiHandler.setAdvancement(LibNames.CRUSH, ModAbilities.CRUSH, ModAbilities.SLASH);
        GuiHandler.setAdvancement(LibNames.PULL, ModAbilities.PULL, ModAbilities.SLASH);
        GuiHandler.setAdvancement(LibNames.PUSH, ModAbilities.PUSH, ModAbilities.SLASH);
        GuiHandler.setAdvancement(LibNames.SLASH, ModAbilities.SLASH, ModAbilities.SLASH);
        GuiHandler.setAdvancement(LibNames.SUFFOCATE, ModAbilities.SUFFOCATE, ModAbilities.SLASH);
        GuiHandler.setAdvancement(LibNames.UPDRAFT, ModAbilities.UPDRAFT, ModAbilities.SLASH);
        GuiHandler.setAdvancement(LibNames.BLACK_FLAME_BALL, ModAbilities.BLACK_FLAME_BALL, ModAbilities.BLACK_FLAME_BALL);
        GuiHandler.setAdvancement(LibNames.BLACK_SCOURING_FLAME, ModAbilities.BLACK_SCOURING_FLAME, ModAbilities.BLACK_FLAME_BALL);
        GuiHandler.setAdvancement(LibNames.BLACK_BLESSING_FLAME, ModAbilities.BLACK_BLESSING_FLAME, ModAbilities.BLACK_FLAME_BALL);
        GuiHandler.setAdvancement(LibNames.BLACK_RAGING_FLAME_BALL, ModAbilities.BLACK_RAGING_FLAME_BALL, ModAbilities.BLACK_FLAME_BALL);
        GuiHandler.setAdvancement(LibNames.BLACK_VOLLEY_FLAME, ModAbilities.BLACK_VOLLEY_FLAME, ModAbilities.BLACK_FLAME_BALL);
        GuiHandler.setAdvancement(LibNames.BLACK_FLARE_FLAME, ModAbilities.BLACK_FLARE_FLAME, ModAbilities.BLACK_FLAME_BALL);
    }
}